### PR TITLE
fix: run-android not finding scripts to overwrite

### LINKED ISSUE #126: ENOENT packager.env when building RN from source during `react-native run-android`
## Environment

```
$ react-native info

  React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.6
      CPU: (4) x64 Intel(R) Core(TM) i5-6600 CPU @ 3.30GHz
      Memory: 726.04 MB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 11.6.0 - /usr/local/bin/node
      Yarn: 1.12.3 - /usr/local/bin/yarn
      npm: 6.5.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 11.4, macOS 10.13, tvOS 11.4, watchOS 4.3
      Android SDK:
        API Levels: 19, 27, 28
        Build Tools: 27.0.3, 28.0.2
        System Images: android-19 | Google APIs Intel x86 Atom, android-25 | Google APIs Intel x86 Atom, android-25 | Google Play Intel x86 Atom, android-27 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 3.1 AI-173.4819257
      Xcode: 9.4/9F1027a - /usr/bin/xcodebuild
    npmPackages:
      react: 16.6.3 => 16.6.3
      react-native: git://github.com/jyrno42/react-native.git#bf64df4aea3f8ecda3fd9cfc2ed25e9f61ac905b => 1000.0.0
    npmGlobalPackages:
      react-native-cli: 2.0.1
```

## Description

I have to manually create the directory `node_modules/@react-native-community/cli/scripts` to get the packager to start when using RN from source. Note, the issue only occurs when running `react-native run-android`.

## Reproducible Demo

1. Clone `https://github.com/Jyrno42/rn-geoloctest`
   - `git clone git@github.com:Jyrno42/rn-geoloctest.git`
2. `yarn`
3. `yarn android`
4. Get the following output:

```
$ yarn android
yarn run v1.12.3
$ react-native run-android
Starting JS server...

ENOENT: no such file or directory, open '/Users/me/Documents/projects/rn-geoloctest/node_modules/@react-native-community/cli/scripts/.packager.env'

Error: ENOENT: no such file or directory, open '/Users/me/Documents/projects/rn-geoloctest/node_modules/@react-native-community/cli/scripts/.packager.env'
    at Object.openSync (fs.js:450:3)
    at Object.writeFileSync (fs.js:1212:35)
    at startServerInNewWindow (/Users/me/Documents/projects/rn-geoloctest/node_modules/@react-native-community/cli/build/runAndroid/runAndroid.js:185:6)
    at isPackagerRunning.then.result (/Users/me/Documents/projects/rn-geoloctest/node_modules/@react-native-community/cli/build/runAndroid/runAndroid.js:77:7)
    at process.internalTickCallback (internal/process/next_tick.js:77:7)

error Command failed with exit code 1.
```
5. Run `mkdir node_modules/@react-native-community/cli/scripts`
6. Run `yarn android` again, packager now starts

### PR DESCRIPTION
**Pull request by grabbou**
Fixes #126 

We need to change this approach, issue tracking in #140.

### CODE REVIEW

**Comment by grabbou** [comment]
I added support for running from React Native source. Note: `run-android` doesn't work for React Native source at the moment anyway. I am going to open an issue to track support for it.

File: packages/cli/src/runAndroid/runAndroid.js [hunk 1]
```diff
@@ -34,20 +33,11 @@ function checkAndroid(root) {
...
 function runAndroid(argv: Array<string>, config: ContextT, args: Object) {
   if (!checkAndroid(args.root)) {
-    const reactNativeScriptsPath = findReactNativeScripts();
-    if (reactNativeScriptsPath) {
-      spawnSync(
-        reactNativeScriptsPath,
-        ['android'].concat(process.argv.slice(1)),
-        { stdio: 'inherit' }
-      );
-    } else {
```
Comment (grabbou) [inline packages/cli/src/runAndroid/runAndroid.js]: CRNA is deprecated, so removing support for it anyway

**Comment by grabbou** [comment]
This is critical bug that has to be shipped with next RC.

File: packages/cli/src/runAndroid/runAndroid.js [hunk 2]
```diff
@@ -215,9 +215,28 @@ function startServerInNewWindow(port, terminal = process.env.REACT_TERMINAL) {
...
+    );
+  } catch (e) {
+    /**
+     * If the `react-native` package is missing, check if we are running from source.
+     *
+     * From `node_modules/@react-native-community/cli/build/run-android to `scripts/`
+     */
+    const possibleScriptLocation = path.resolve(
+      __dirname,
+      `../../../../../scripts/${scriptFile}`
```
Comment (thymikee) [inline packages/cli/src/runAndroid/runAndroid.js]: or you could add a new flag `pathToReactNative` which you could pass to RNTester scripts?

Comment (grabbou) [reply packages/cli/src/runAndroid/runAndroid.js]: Yeah, I think this is a good idea and would solve few other issues we had already in `start` command. Let me rewrite it by adding global `--pathToReactNative` flag (similar to root) so that users can pass it and we can decide where to use it.

This is amazing for debugging too!

File: packages/cli/src/runAndroid/runAndroid.js [hunk 3]
```diff
@@ -220,21 +212,24 @@ function startServerInNewWindow(port, terminal = process.env.REACT_TERMINAL) {
...
-    __dirname,
-    '..',
-    '..',
-    'scripts',
-    packagerEnvFilename
+  /**
+   * Set up the `.packager.(env|bat)` file to ensure the packager starts on the right port.
+   */
+  const launchPackagerScript = require.resolve(
+    `react-native/scripts/${scriptFile}`
```
Comment (thymikee) [inline packages/cli/src/runAndroid/runAndroid.js]: a reminder to convert this path to a flag passed to `run-android`/`run-ios` command
