### PR TITLE
fix: --appFolder should only install specific app on Android.

### LINKED ISSUE #32: --appFolder on Android not really working as expected
Let's say you have more than 1 app in your android directory. When you do:

```bash
react-native run-android --appFolder someAppFolder
```

It is installing all apps. This is because under the hood the cli is running `./gradlew installDebug`. (or whatever variant). Instead it should be:

```bash
./gradlew :someAppFolder:installDebug
```

### PR DESCRIPTION
**Pull request by ferrannp**
Fixes #32.

Extracting bunch of functions to its own files too + adding tests.

For not being a breaking change, default behavior (without passing `--appFolder`) will be just to call `installDebug`.

### CODE REVIEW

**Comment by thymikee** [comment]
Mind adding a test for that?

**Comment by ferrannp** [comment]
Is there any test for this whole file?

**Comment by thymikee** [comment]
Dunno, but it's worth to add it anyway, would make for an amazing contribution :)

**Comment by ferrannp** [comment]
Ok, gonna give it a chance. Then try to focus on other super urgent issues before release 😄

File: packages/local-cli/runAndroid/runOnAllDevices.js [hunk 1]
```diff
@@ -0,0 +1,117 @@
...
+  packageName,
+  adbPath
+) {
+  try {
+    const gradleArgs = [];
+    if (args.variant) {
+      gradleArgs.push(
+        `${
+          args.appFolder
+        }:install${args.variant[0].toUpperCase()}${args.variant.slice(1)}`
```
Comment (grabbou) [inline packages/local-cli/runAndroid/runOnAllDevices.js]: This change has a minor breaking change that we should be aware of. I am not sure which approach is the desired one - we should probably check it and decide what is the way we want to keep it.

`args.appFolder` is an optional CLI flag that defaults to "app". Prior to this PR, we were not using this option at all, making it impossible to change the app to install on the device, when multiple are defined. 

The command executed by Gradle was always e.g: "installDebug", where in reality, it should've been "app:installDebug", since the "appFolder" defaults to "app". 

That means, after this PR is merged, all the default executions will contain "app:". This might be breaking for people that were depending on this undocumented bug.

I wonder whether we should stick to it, or remove the default "app" value of "appFolder" and make it either "appFolder:installDebug" or "installDebug", depending on whether it is passed to the CLI.

Comment (janicduplessis) [reply packages/local-cli/runAndroid/runOnAllDevices.js]: Yea I think it would be better to default to keep running `installDebug` if `appFolder` is not specified.

Comment (ferrannp) [reply packages/local-cli/runAndroid/runOnAllDevices.js]: Seems reasonable, I will make that change.
