### PR TITLE
fix: normalize paths for Gradle on Windows

### LINKED ISSUE #129: Wrong path in settings.gradle when linking dependency on Windows
## Environment

react-native: 0.58.1

System:
      OS: Windows 10
      CPU: (8) x64 Intel(R) Core(TM) i7-4712HQ CPU @ 2.30GHz
      Memory: 6.09 GB / 15.91 GB
    Binaries:
      Yarn: 1.13.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.7.0 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.3.0.0 AI-182.5107.16.33.5199772

## Description
Expected path in `android/settings.gradle`:

```
project(':react-native-gesture-handler').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-gesture-handler/android')
```

Actual path:

```
project(':react-native-gesture-handler').projectDir = new File(rootProject.projectDir, '..\node_modules\react-native-gesture-handler\android')
```

Because of backslashes, running `react-native run-android` fails.

Note, that this works as expected in react-native 0.57.8, because there's additional code:

```js
/*
   * Fix for Windows
   * Backslashes is the escape character and will result in
   * an invalid path in settings.gradle
   * https://github.com/rnpm/rnpm/issues/113
   */
  if (isWin) {
    projectDir = projectDir.replace(/\\/g, '/');
  }
```

See https://unpkg.com/react-native@0.57.8/local-cli/link/android/patches/makeSettingsPatch.js

There's no such a fix for Windows in 0.58.1, see https://unpkg.com/react-native@0.58.1/local-cli/link/android/patches/makeSettingsPatch.js

I've checked History and Blame on that file in this repo, but didn't find any trace of that fix.

Let me know if that's appropriate place to submit local-cli issues, since I'm not sure about that.

Also, I can submit a PR reverting that fix.

## Reproducible Demo

Steps to reproduce:

1. install package (e.g. `yarn add react-native-gesture-handler`)
2. link package (`react-native link react-native-gesture-handler`)

### PR DESCRIPTION
**Pull request by thymikee**
Summary:
---------

Fixes #129

Test Plan:
----------

I added a test that simulates Windows on POSIX machines, because we don't run our tests on Windows.
@cherniavskii can you test this on a Windows machine?

### CODE REVIEW

File: packages/cli/src/link/__tests__/android/makeSettingsPatch-test.js [hunk 1]
```diff
@@ -4,78 +4,98 @@
...
+    ).toMatchObject({
+      pattern: '\n',
+      patch: expect.any(String),
+    });
   });
 
-  it('should make a correct patch', () => {
-    const projectDir = path.relative(
-      path.dirname(projectConfig.settingsGradlePath),
-      dependencyConfig.sourceDir
```
Comment (thymikee) [inline packages/cli/src/link/__tests__/android/makeSettingsPatch-test.js]: gotta love these tests that recreate implementation 1-to-1 :D
